# Child elements are indented with two spaces from their parent.
# Repeating items are shown with a dash in front.
version: 0.0.1

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 8888
  adminConnectors:
  - type: http
    port: 9999